public class ContactAndLeadSearch {
    public static  List<List< SObject>> searchContactsAndLeads(String searchText){
        List<List<sObject>> searchList = [FIND :searchText IN ALL FIELDS 
                                          RETURNING Contact(FirstName,LastName),
                                          Lead(FirstName,LastName)];
        Contact[] searchContacts = (Contact[])searchList[0];
        Lead[] searchLeads = (Lead[])searchList[1];
        for (Contact c : searchContacts) {
            System.debug(c.LastName + ', ' + c.FirstName);
        }
        for (Lead l : searchLeads) {
            System.debug(l.LastName + ', ' + l.FirstName);
        }
        return searchList;
    }
}